// Layout effects all pages
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./ui/globals.css";

import Header from "../components/header";
import Footer from "../components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Book Tracker - Zach Kurfirst",
  description: "Book tracker generated by create next app.",
};

export default function RootLayout({
  // children -> pages
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased text-slate-900 dark:text-slate-100 bg-gradient-to-b from-slate-200 to-slate-50 dark:from-slate-950 dark:to-slate-900 flex min-h-screen flex-col p-12 items-center`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
